name: tomato_timer
description: Tomato Timer Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_form_builder: ^9.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.2
  flutter_native_splash: ^2.3.10
  flutter_stepindicator: ^0.1.7
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^9.1.0
  intl: ^0.18.1
  step_progress_indicator: ^1.0.2
  stop_watch_timer: ^3.1.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900


  assets:
    - assets/svg/logo/
    - assets/svg/persons/
    - assets/svg/icons/
